/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testandroid_MainActivity */

#ifndef _Included_com_example_testandroid_MainActivity
#define _Included_com_example_testandroid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_testandroid_MainActivity_initializeFaceDetector
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_testandroid_MainActivity_detectFace
        (JNIEnv *, jobject, jbyteArray, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
